version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procurement-analytics-dev
    ports:
      - "8501:8501"
    volumes:
      # Mount parent CSV as read-only
      - ../PO_Data.csv:/app/data/PO_Data.csv:ro
      # Mount entire app directory for live reload during development
      - ./:/app
      # Exclude Python cache from mount
      - /app/__pycache__
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_RUN_ON_SAVE=true  # Auto-reload on file changes
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll  # Better for Docker
    restart: unless-stopped
    command: >
      streamlit run app.py
      --server.address=0.0.0.0
      --server.port=8501
      --server.runOnSave=true
      --server.fileWatcherType=poll
    networks:
      - analytics-network

networks:
  analytics-network:
    driver: bridge
