version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procurement-analytics
    ports:
      - "${HOST_PORT:-8501}:8501"  # Default 8501, override with HOST_PORT env var
    volumes:
      # Mount parent CSV as read-only
      - ../PO_Data.csv:/app/data/PO_Data.csv:ro
      # Mount upload directory for user uploads (persistent)
      - ./data/uploads:/app/data/uploads
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - analytics-network

networks:
  analytics-network:
    driver: bridge
